<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recs.Application\Recs.Application.csproj" />
    <ProjectReference Include="..\Recs.Infrastructure\Recs.Infrastructure.csproj" />
    <ProjectReference Include="..\Recs.ML\Recs.ML.csproj" />
  </ItemGroup>

</Project>
